"""Stage 5: Model evaluation — multi-model comparison and reporting."""

import json
import time
from pathlib import Path

import structlog

from vision_workbench.core.base import BaseStage
from vision_workbench.core.config import EvaluateStageConfig
from vision_workbench.core.context import ContextKey, PipelineContext
from vision_workbench.core.result import StageResult

logger = structlog.get_logger(__name__)


class EvaluateStage(BaseStage[EvaluateStageConfig, StageResult]):
    """Compare multiple model checkpoints and generate evaluation reports.

    Produces PR curves, ROC curves, confusion matrices, latency profiling,
    and a comprehensive evaluation report (Markdown/HTML/JSON).
    """

    name = "evaluate"
    description = "Multi-model comparison, curves, profiling, and reporting"
    depends_on = ["validate"]

    def validate_inputs(self, ctx: PipelineContext) -> tuple[bool, list[str]]:
        missing = []
        if not ctx.get(ContextKey.VAL_METRICS):
            missing.append(ContextKey.VAL_METRICS)
        return len(missing) == 0, missing

    def run(self, config: EvaluateStageConfig, ctx: PipelineContext) -> tuple[StageResult, PipelineContext]:
        t0 = time.perf_counter()
        metrics = ctx.get(ContextKey.VAL_METRICS, {})
        logger.info("evaluate.stage.start", metrics=metrics)

        workspace = Path(ctx.get("runtime.workspace", "./vw_workspace"))
        report_dir = workspace / "reports" / "evaluation_reports"
        report_dir.mkdir(parents=True, exist_ok=True)

        # Generate report
        report = self._generate_report(metrics, config.curves)
        report_path = report_dir / "evaluation_report.md"
        with open(report_path, "w") as f:
            f.write(report)

        dt = time.perf_counter() - t0
        result = StageResult(
            stage_name="evaluate", success=True, duration_seconds=dt,
            artifacts={"evaluation_report": str(report_path)},
            metrics=metrics,
        )
        ctx = ctx.evolve(**{ContextKey.EVAL_REPORT: str(report_path)})
        ctx = ctx.record_stage("evaluate", success=True, duration_seconds=dt)
        return result, ctx

    def dry_run(self, config: EvaluateStageConfig, ctx: PipelineContext) -> dict:
        return {"action": "evaluate_model", "curves": config.curves}

    def _generate_report(self, metrics: dict, curves: list[str]) -> str:
        lines = [
            "# Model Evaluation Report",
            "",
            "## Metrics",
            "",
            "| Metric | Value |",
            "|--------|-------|",
        ]
        for k, v in metrics.items():
            if isinstance(v, (int, float)):
                lines.append(f"| {k} | {v:.4f} |")
        lines += [
            "",
            "## Curves",
            "",
            f"Requested curves: {', '.join(curves)}",
            "",
            "*Generated by Vision Workbench*",
        ]
        return "\n".join(lines)
