"""Stage 3: Validation + evaluation — metrics, confusion matrix, PR curves."""

import json
import time
from pathlib import Path

import structlog

from vision_workbench.core.base import BaseStage
from vision_workbench.core.config import ValidateStageConfig
from vision_workbench.core.context import ContextKey, PipelineContext
from vision_workbench.core.exceptions import StageExecutionError
from vision_workbench.core.result import StageResult

logger = structlog.get_logger(__name__)


class ValidateStage(BaseStage[ValidateStageConfig, StageResult]):
    """Validate a trained model and generate evaluation reports.

    Runs Ultralytics model.val(), extracts metrics, generates
    confusion matrix and PR curve plots.
    """

    name = "validate"
    description = "Model validation, metric extraction, confusion matrix, PR curves"
    depends_on = ["train"]

    def validate_inputs(self, ctx: PipelineContext) -> tuple[bool, list[str]]:
        missing = []
        if not ctx.get(ContextKey.CHECKPOINT_PATH):
            missing.append(ContextKey.CHECKPOINT_PATH)
        if not ctx.get(ContextKey.DATASET_DIR):
            missing.append(ContextKey.DATASET_DIR)
        return len(missing) == 0, missing

    def run(self, config: ValidateStageConfig, ctx: PipelineContext) -> tuple[StageResult, PipelineContext]:
        t0 = time.perf_counter()
        ckpt = ctx.get(ContextKey.CHECKPOINT_PATH)
        dataset_dir = Path(ctx.get(ContextKey.DATASET_DIR, "."))
        dataset_yaml = dataset_dir / "dataset.yaml"

        if not Path(ckpt).exists():
            dt = time.perf_counter() - t0
            return StageResult(stage_name="validate", success=False, error_message=f"Checkpoint not found: {ckpt}", duration_seconds=dt), ctx

        try:
            from ultralytics import YOLO
        except ImportError:
            raise StageExecutionError("Ultralytics not installed. Run: pip install ultralytics")

        logger.info("validate.start", checkpoint=ckpt, data=str(dataset_yaml))

        model = YOLO(str(ckpt))
        results = model.val(
            data=str(dataset_yaml),
            split=config.split,
            conf=config.conf,
            iou=config.iou,
            plots=config.plots,
        )

        # Extract core metrics
        metrics = {
            "mAP_0.5:0.95": float(getattr(results.box, "map", 0) or 0),
            "mAP_0.5": float(getattr(results.box, "map50", 0) or 0),
            "mAP_0.75": float(getattr(results.box, "map75", 0) or 0),
            "precision": float(getattr(results.box, "mp", 0) or 0),
            "recall": float(getattr(results.box, "mr", 0) or 0),
        }

        # Save metrics
        workspace = Path(ctx.get("runtime.workspace", "./vw_workspace"))
        report_dir = workspace / "reports"
        report_dir.mkdir(parents=True, exist_ok=True)

        metrics_path = report_dir / "validation_metrics.json"
        with open(metrics_path, "w") as f:
            json.dump(metrics, f, indent=2)

        # Generate Markdown report
        report_path = report_dir / "validation_report.md"
        self._write_report(report_path, metrics, config)

        dt = time.perf_counter() - t0
        result = StageResult(
            stage_name="validate", success=True, duration_seconds=dt,
            artifacts={"metrics_json": str(metrics_path), "report": str(report_path)},
            metrics=metrics,
        )
        ctx = ctx.evolve(**{ContextKey.VAL_METRICS: metrics})
        ctx = ctx.record_stage("validate", success=True, duration_seconds=dt)
        return result, ctx

    def dry_run(self, config: ValidateStageConfig, ctx: PipelineContext) -> dict:
        return {"action": "validate_model", "split": config.split}

    def _write_report(self, path: Path, metrics: dict, config: ValidateStageConfig) -> None:
        lines = [
            "# Model Validation Report\n",
            "## Metrics\n",
            "| Metric | Value |",
            "|--------|-------|",
        ]
        for k, v in metrics.items():
            lines.append(f"| {k} | {v:.4f} |" if isinstance(v, float) else f"| {k} | {v} |")
        lines += [
            "\n## Parameters\n",
            f"- Split: `{config.split}`",
            f"- Confidence threshold: {config.conf}",
            f"- IoU threshold: {config.iou}",
            f"- Plots generated: {config.plots}",
            "\n*Generated by Vision Workbench*",
        ]
        with open(path, "w") as f:
            f.write("\n".join(lines))
